Use git diff to search for changelog entry

diff --git a/tools/check-changelog b/tools/check-changelog
--- a/tools/check-changelog
+++ b/tools/check-changelog
@@ -1,22 +1,15 @@
 #!/bin/sh
 
-echo "looking for change log of $CI_MERGE_REQUEST_IID"
+echo "looking for change log"
 
-count=0
-for i in add remove fix security skip; do
-    [ -f changelog.d/"$CI_MERGE_REQUEST_IID"."$i" ]
-    retcode=$?
-    if [ $retcode -eq 0 ]; then
-        echo "found $CI_MERGE_REQUEST_IID.$i"
-        count=$(( count + 1 ))
-    else
-        echo "no $CI_MERGE_REQUEST_IID.$i"
-    fi
-done
-if [ $count -gt 0 ]; then
-    echo "ok"
+git diff --raw $CI_MERGE_REQUEST_TARGET_BRANCH_NAME HEAD -- changelog.d | \
+    grep ' A\t' | grep '\.\(skip\|add\|remove\|fix\|security\)$'
+ret=$?
+
+if [ $ret -eq 0 ]; then
+    echo "found a changelog entry"
     exit 0
 else
-    echo "must have a changelog entry or explicitly skip it"
+    echo "changelog entry not found"
     exit 1
 fi
